FROM ubuntu:18.04 AS build

# Instalación de paquetes necesarios, limpieza de cache y archivos temporales
RUN apt-get update && \
    apt-get install -y wget git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /root

RUN cd ~ && wget -O - "https://github.com/tsenart/vegeta/releases/download/v12.11.0/vegeta_12.11.0_linux_amd64.tar.gz" | tar xzf - -C /usr/bin/ && \
git clone https://github.com/aiortc/aioquic.git && \
git clone https://github.com/nicovell3/DNSWaterTorture.git

FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

# Instalación de paquetes necesarios, limpieza de cache y archivos temporales
RUN apt-get update && \
    apt-get install -y python3 nano net-tools openssh-server sudo supervisor hping3 python3-pip dnsutils libssl-dev tcpdump golang tmux && \
    pip3 install scapy==2.4.0 asgiref dnslib httpbin starlette wsproto peewee donna25519 tqdm requests dnspython && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# Creamos el nuevo usuario con su contraseña y lanzamos el servicio ssh
RUN useradd -m -s /bin/bash -g root -G sudo -u 1000 cognet  && \
echo "cognet:supercognet" | chpasswd && \
#sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
#echo 'root:root' | chpasswd && \
service ssh start


# Establece el directorio de trabajo dentro del contenedor
WORKDIR /home/cognet
# Copia los archivos del directorio /app al directorio de trabajo del contenedor
COPY /app .
# Copia los archivos necesarios desde la etapa de construcción
COPY --from=build /usr/bin/vegeta /usr/bin/vegeta
COPY --from=build /root /home/cognet
# Agrega configuración para supervisord
COPY supervisord/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

#Configurar el display
ENV DISPLAY=host.docker.internal:0.0
RUN echo 'X11Forwarding yes' >> /etc/ssh/sshd_config


# Inicia supervisord en primer plano para evitar cierre de contenedor
CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]