FROM ubuntu:18.04 AS build

# Instalación de paquetes necesarios, limpieza de cache y archivos temporales
RUN apt-get update && \
    apt-get install -y  wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /root

RUN cd ~ && wget -O - "https://go.dev/dl/go1.21.1.linux-amd64.tar.gz" | tar xzf - -C /usr/local/ 


FROM ubuntu:18.04

# Instalación de paquetes necesarios, limpieza de cache y archivos temporales
RUN apt-get update && \
    apt-get install -y python3 openssh-server sudo supervisor hping3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# Creamos el nuevo usuario con su contraseña y lanzamos el servicio ssh
RUN useradd -m -s /bin/bash -g root -G sudo -u 1000 cognet  && \
echo "cognet:supercognet" | chpasswd && \
#sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
#echo 'root:root' | chpasswd && \
service ssh start


# Establece el directorio de trabajo dentro del contenedor
WORKDIR /home/cognet
# Copia los archivos del directorio /app al directorio de trabajo del contenedor
COPY /app .
# Copia los archivos necesarios desde la etapa de construcción
COPY --from=build /usr/local/go /usr/local/go
# Agrega configuración para supervisord
COPY supervisord/supervisord.conf /etc/supervisor/conf.d/supervisord.conf


# Configuramos el PATH para ejecutar go en esta etapa
ENV PATH="/usr/local/go/bin:$PATH"
# Configuramos el PATH para el usuario "cognet" e instalamos vegeta
RUN echo 'export PATH=$PATH:/usr/local/go/bin' >> /home/cognet/.bashrc && \
go mod init vegeta_workspace && \
go get -u github.com/tsenart/vegeta


# Inicia supervisord en primer plano para evitar cierre de contenedor
CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]