FROM ubuntu:18.04

# Instalación de paquetes necesarios, limpieza de cache y archivos temporales
RUN apt-get update && \
    apt-get install -y python3 nano net-tools openssh-server sudo supervisor nginx tcpdump bind9 bind9utils bind9-doc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# Creamos el nuevo usuario con su contraseña y lanzamos el servicio ssh
RUN useradd -m -s /bin/bash -g root -G sudo -u 1000 cognet  && \
echo "cognet:supercognet" | chpasswd && \
#sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
#echo 'root:root' | chpasswd && \
service ssh start


# Modifica el archivo para agregar la opción "-4" a OPTIONS
RUN sed -i 's/^OPTIONS="-u bind"$/OPTIONS="-u bind -4"/' /etc/default/bind9 

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /home/cognet
# Agrega configuración para supervisord
COPY supervisord/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/html /home/cognet/
COPY bind9/ /etc/bind/

# Inicia supervisord en primer plano para evitar cierre de contenedor
CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
